### ISSUE TITLE
Add to bosh.io

### ISSUE THREAD

**Issue by drnic** [hybris/nxlog-boshrelease#1]
Any objections to this bosh release being added to https://bosh.io/releases registry?

Email Dmitriy/@cppforlife if you'd like to add it to the list. It also creates nice per-job pages for how to use it e.g. http://bosh.cloudfoundry.org/jobs/grafana?source=github.com/vito/grafana-boshrelease&version=1

**Comment by renewelches** [comment]
in general not, I just started the SAP open source process for this release and the Riemann and Riemann-tools releases.
I will keep you posted as soon as I have it official.

**Comment by jhunt** [comment]
Looks like this got added to https://bosh.io/releases at some point.

http://bosh.io/releases/github.com/hybris/nxlog-boshrelease?all=1
